name: Aggregate Capacities Data

on:
  schedule:
    - cron: '0 22-23,0-15 * * *'   # Runs daily at midnight UTC
  workflow_dispatch:       # Also allow manual triggering

jobs:
  aggregate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all commit history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies (if needed)
        run: pip install --upgrade pip

      - name: Run aggregation script
        run: python scripts/aggregate.py

      - name: Commit and push aggregated data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add aggregated_capacities.json
          git diff-index --quiet HEAD || git commit -m "Update aggregated capacities data"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

